### ISSUE TITLE
Temperaturanzeige abhängig von der Spannungversorgung

### ISSUE THREAD

**Issue by MauriceMarkhoff** [TUBSAPISS2018/API-Materialien#1]
Die Temperaturanzeige variiert je nach dem ob die Spannungversorgung über Batterie oder USB erfolgt

**Comment by Marc-K** [comment]
Das Verhalten ist bekannt und kann von uns leider nicht geändert werden, da es sich um ein sensorspezifisches Problem handelt. Auf der Funduino-Homepage wird [in diesem Tutorial](https://funduino.de/nr-9-temperatur-messen) empfohlen eine externe Stromversorgung zu verwenden:

"Bei dem Aufbau sollte nach Möglichkeit eine externe Stromversorgung verwendet werden, da dies die Sensorgenauigkeit wesentlich verbessert."

**Comment by uPrizZ** [comment]
Danke!
